apiVersion: apps/v1
kind: Deployment
metadata:
  name: jslay-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jslay-net
  template:
    metadata:
      labels:
        app: jslay-net
        version: GIT_COMMIT
    spec:
      initContainers:
        - name: builder
          image: busybox:1.32.0
          command: ['sh', '-c',
                    "wget https://github.com/REPO_USER/REPO_NAME/archive/GIT_COMMIT.zip && \
                    unzip -d /tmp GIT_COMMIT.zip && \
                    cp -R /tmp/REPO_NAME-GIT_COMMIT/COPY_DIR/* /nginx/"]
          volumeMounts:
            - mountPath: /nginx
              name: site
      containers:
        - name: jslay-net
          image: nginx:stable-alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: site
      volumes:
        - name: site
          emptyDir: {}
