apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jslay-net
#  annotation:
#    kubernetes.io/ingress.class: "nginx"
#    kubernetes.io/issuer: "letsencrypt"
#    kubernetes.io/acme-challenge-type: "http01"
spec:
#  tls:
#  - hosts:
#    - jslay.net
#    secretName: jslay-net-tls
  rules:
  - host: jslay.net
    http:
      paths:
      - path: /
        backend:
         serviceName: jslay-net
         servicePort: 80
    