apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jslay-net
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - jslay.net
    secretName: jslay-net-tls
  rules:
  - host: jslay.net
    http:
      paths:
      - path: /
        backend:
         serviceName: jslay-net
         servicePort: 80
    