apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: REPO_NAME
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - HOST
    secretName: REPO_NAME-tls
  rules:
  - host: HOST
    http:
      paths:
      - path: /
        backend:
         serviceName: REPO_NAME
         servicePort: 80
    